version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: taskmanager_postgres
    restart: always
    environment:
      POSTGRES_USER: task_user
      POSTGRES_PASSWORD: task_password
      POSTGRES_DB: task_manager
    ports:
      - "5432:5432"
    volumes:
      - taskmanager_pgdata:/var/lib/postgresql/data

volumes:
  taskmanager_pgdata: